sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.7
    env:
    - PYTHON_VERSION="3.7"
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:O:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda create --yes --quiet -n colour-datasets-ci python=${PYTHON_VERSION} coverage coveralls flake8 mock nose tqdm xlrd
  - source activate colour-datasets-ci
  - conda install -y -c conda-forge colour-science

script:
  - flake8 colour_datasets
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE --with-coverage --cover-package=colour_datasets colour_datasets

after_success:
  - coveralls
